spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demention;MODE=MySQL
    username: sa
    password:

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: ture
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379
      password: ${TEST_REDIS_PASSWORD}

logging.level:
  org.hibernate.SQL: debug